// @vitest-environment node
//
// The daily feedback brief — issue 248 step 2.
//
// What these pin, and why each mattered enough to pin:
//
//   1. THE PREMISE THAT WAS WRONG. The 247 scout judged 25 of 28 open reports
//      unlocatable, measuring TITLES and character counts. The descriptions
//      average 147 characters; the titles are the thin part. So the matcher
//      reads the description first, and there is a test whose fixture has a
//      deliberately useless title and a rich description — it is the assertion
//      that the correction actually took.
//   2. THE HONESTY RULE. A confident wrong pointer is worse than silence,
//      because the reader trusts it and loses a morning in the wrong file. So
//      "cannot place this" is asserted as a real, printed output, and the
//      corroboration rules that stop a confident guess are pinned by the two
//      real-world cases that defeated the first implementation.
//   3. ONE DEFINITION OF OPEN AND STALE. Still issue 233's. The brief regroups
//      for reading order; it must never re-derive what open or stale mean.
//   4. THE HEARTBEAT ALLOWLIST. digest_runs now has two writers. Before the
//      label filter, one feedback-brief row would have made a DEAD webhook
//      digest look alive to system-health, silently disarming the alarm that
//      catches a deployment-pinned cron.
import { describe, it, expect, vi, beforeEach } from 'vitest'
import { readFileSync } from 'node:fs'
import {
  buildPlacementIndex, placeFeedbackItem, tokenize, normalizeText,
  type ScreenMapEntry,
} from '@/lib/feedback-placement'
import { buildFeedbackBrief, mistypeFlag, type BriefItem } from '@/lib/feedback-brief'
import { summarizeFeedbackQueues } from '@/lib/feedback-queues'

const map = JSON.parse(readFileSync('docs/screen-map.json', 'utf8')) as { entries: ScreenMapEntry[] }
const index = buildPlacementIndex(map.entries)

const NOW = new Date('2026-08-15T12:00:00Z').getTime()
const daysAgo = (n: number) => new Date(NOW - n * 86400000).toISOString()

const item = (o: Partial<BriefItem> & { createdDays?: number; touchedDays?: number } = {}): BriefItem => {
  const { createdDays = 3, touchedDays, ...rest } = o
  return {
    id: o.id ?? 'x',
    type: 'bug',
    status: 'submitted',
    title: 'a title',
    description: 'a description',
    submitter: 'Ankur Patel',
    location: 'Palm Beach',
    is_internal: false,
    created_at: daysAgo(createdDays),
    updated_at: daysAgo(touchedDays ?? createdDays),
    ...rest,
  }
}

const build = (items: BriefItem[]) => buildFeedbackBrief({ items, index, now: NOW, appUrl: 'https://hub.test' })

// ─────────────────────────────────────────────────────────────────────
describe('placement — it reads the DESCRIPTION, not the title', () => {
  // THE CORRECTION, AS AN ASSERTION. This title is pure noise — it is in fact
  // the composer's autogenerated title, which is what several real rows carry.
  // Everything locating is in the description.
  const uninformativeTitle = item({
    title: 'Problem with Engagement – Aug 2026',
    description:
      "This file went to the main hive, was put into my book, but it's showing up in the " +
      'assessment/request column in the engagement tab. This should be in the inbox (new) tab',
  })

  it('places an item whose title says nothing and whose description says plenty', () => {
    const p = placeFeedbackItem(uninformativeTitle, index)
    expect(p.confidence).not.toBe('none')
    expect(p.candidates.length).toBeGreaterThan(0)
    expect(p.candidates.map(c => c.id)).toContain('clients.inbox')
  })

  it('THE PROOF IT IS THE DESCRIPTION DOING THE WORK: blank it and the placement collapses', () => {
    // Same row, same title, no description. If the title were carrying the
    // placement this would still resolve — and the 247 premise would have been
    // right after all.
    const titleOnly = { ...uninformativeTitle, description: '' }
    const p = placeFeedbackItem(titleOnly, index)
    expect(p.candidates.map(c => c.id)).not.toContain('clients.inbox')
  })

  it('a title alone cannot reach confident', () => {
    const p = placeFeedbackItem(
      { title: 'the kanban board columns and the inbox new leads badge', description: '' },
      index,
    )
    expect(p.confidence).not.toBe('confident')
  })
})

describe('placement — an item that cannot be placed SAYS SO', () => {
  it('returns none, with no candidates, for a description carrying nothing', () => {
    // Real row: title 'bigger font for us "tenured" bees', description 'pleawe'.
    const p = placeFeedbackItem({ title: 'bigger font for us "tenured" bees', description: 'pleawe' }, index)
    expect(p.confidence).toBe('none')
    expect(p.candidates).toEqual([])
  })

  it('the unplaced result carries NO file path — the caller cannot guess from it', () => {
    const p = placeFeedbackItem({ title: '', description: 'zzz qqq' }, index)
    expect(p.candidates).toHaveLength(0)
  })

  it('a bug that cannot be placed prints the follow-up line rather than a file', () => {
    const brief = build([
      item({ type: 'bug', title: 'bigger font', description: 'pleawe', createdDays: 0 }),
    ])
    expect(brief.text).toContain('not enough to place — needs a follow-up question')
  })

  it('an unplaceable FEATURE prints nothing rather than reaching', () => {
    // "Thumbtack integration" points nowhere because it does not exist yet.
    // Silence is the right output; a line would be padding.
    const brief = build([
      item({
        type: 'feature', title: 'Thumbtack Integration', createdDays: 0,
        description: 'I currently use Thumbtack for leads and all leads feed directly into Jobber.',
      }),
    ])
    expect(brief.text).not.toContain('not enough to place')
  })
})

describe('placement — the honesty rule, pinned by the cases that broke it', () => {
  // Both of these were CONFIDENT and WRONG in the first implementation.
  it('does not place an automated-email complaint on Settings→Location', () => {
    const p = placeFeedbackItem({
      title: 'Client was pushed an appreciation email that I never created',
      description:
        'I had a client forward an email thanking them for their recent business and offering a ' +
        'discount for a google review.  It also said they would be receiving an invoice soon.  ' +
        'I did not create this email and have no idea how many people it went to.  ' +
        'Is there a way to know?  Thank you!',
    }, index)
    // The word "business" collided with "my business details". A shortlist is
    // honest; naming that one file was not.
    expect(p.confidence).not.toBe('confident')
  })

  it('does not place a push-to-Jobber request on Settings→Profile', () => {
    const p = placeFeedbackItem({
      title: 'automatic add to jobber',
      description:
        'It would be great if the schedule an assessment request could automatically go to jobber. ' +
        'They are booking with the link provided already',
    }, index)
    expect(p.confidence).not.toBe('confident')
  })

  it("the product's own name places nothing", () => {
    // "bee"/"hub" appear in the map and are rare there, so IDF alone made them
    // decisive — and every owner writes "Bee Hub" about everything.
    expect(tokenize('I would like this to come into the Bee Hub')).not.toContain('bee')
    expect(tokenize('I would like this to come into the Bee Hub')).not.toContain('hub')
    const p = placeFeedbackItem({ title: 'Quo', description: 'I would like to dial out from Bee Hub' }, index)
    expect(p.candidates.map(c => c.id)).not.toContain('shell.ask-bee-hub')
  })

  it('every candidate rests on two words or one distinctive one — never on padding', () => {
    const p = placeFeedbackItem({ title: '', description: 'Snooze not available in Client section' }, index)
    // 'section' and 'client' are ordinary; there is no snooze surface in the
    // map. Three candidates built from that was padding.
    for (const c of p.candidates) expect(c.matched.length).toBeGreaterThan(0)
    expect(p.candidates.length).toBeLessThanOrEqual(3)
  })

  it('contractions are grammar, not evidence', () => {
    expect(normalizeText("it isn't showing")).toBe('it isnt showing')
    expect(tokenize("she isn't showing up and I haven't scheduled")).not.toContain('isnt')
  })

  it('a shortlist is at most three, and every candidate names its matched words', () => {
    const p = placeFeedbackItem({
      title: 'Additional Address',
      description:
        'I would like to add an additional/new address for an existing client, and I do not see ' +
        'an option to add a new address for her. She is moving soon.',
    }, index)
    expect(p.candidates.length).toBeLessThanOrEqual(3)
    for (const c of p.candidates) {
      expect(c.matched.length).toBeGreaterThan(0)
      expect(c.file).toBeTruthy()
    }
  })
})

describe('placement — a description that names a screen resolves to a map entry', () => {
  it('resolves and the entry is a real one from the map', () => {
    const p = placeFeedbackItem({
      title: 'x',
      description:
        'When entering a new lead on your phone, especially iPhone, the keyboard covers up the ' +
        'areas you need to type in, makes entering information slow, and I have to ask client ' +
        'same information again. Zee Bee comes off as incompetent',
    }, index)
    expect(p.confidence).toBe('confident')
    const ids = new Set(map.entries.map(e => e.id))
    for (const c of p.candidates) expect(ids.has(c.id)).toBe(true)
  })

  it('a placement always points at a file that the map says exists', () => {
    const byId = new Map(map.entries.map(e => [e.id, e]))
    const p = placeFeedbackItem({
      title: 'x',
      description: 'the notifications for new leads go to everyone, not just the assigned person',
    }, index)
    for (const c of p.candidates) expect(c.file).toBe(byId.get(c.id)!.file)
  })
})

// ─────────────────────────────────────────────────────────────────────
describe('the brief uses the EXISTING queue helper, not a new one', () => {
  const items = [
    item({ id: 'a', status: 'submitted', createdDays: 0 }),
    item({ id: 'b', status: 'under_review', createdDays: 40, touchedDays: 20 }),
    item({ id: 'c', status: 'in_progress', createdDays: 5 }),
    item({ id: 'd', status: 'planned', createdDays: 10, touchedDays: 1 }),
    item({ id: 'e', status: 'shipped', createdDays: 30 }),
    item({ id: 'f', status: 'declined', createdDays: 30 }),
  ]

  it('its summary IS summarizeFeedbackQueues, value for value', () => {
    const brief = build(items)
    expect(brief.summary).toEqual(summarizeFeedbackQueues(items, NOW))
  })

  it('open count matches the shared definition, and closed items never appear', () => {
    const brief = build(items)
    expect(brief.openCount).toBe(4)
    const listed = brief.groups.flatMap(g => g.lines).map(l => l.item.id)
    expect(listed).not.toContain('e')
    expect(listed).not.toContain('f')
  })

  it('staleness comes from the shared predicate — 14 days untouched', () => {
    const brief = build(items)
    expect(brief.summary.counts.stale).toBe(1)
  })
})

describe('grouping and order', () => {
  const items = [
    item({ id: 'bug-young', type: 'bug', createdDays: 2, title: 'young bug' }),
    item({ id: 'bug-old', type: 'bug', createdDays: 30, title: 'old bug' }),
    item({ id: 'feat', type: 'feature', createdDays: 9, title: 'a feature' }),
    item({ id: 'dec', type: 'decision', is_internal: true, createdDays: 5, title: 'a decision' }),
    item({ id: 'haz', type: 'hazard', is_internal: true, createdDays: 4, title: 'a hazard' }),
    item({ id: 'new', type: 'bug', createdDays: 0, title: 'brand new' }),
  ]

  it('bugs lead, then features, then decisions, then hazards', () => {
    const brief = build(items)
    const t = brief.text
    expect(t.indexOf('*BUGS*')).toBeGreaterThan(-1)
    expect(t.indexOf('*BUGS*')).toBeLessThan(t.indexOf('*FEATURES*'))
    expect(t.indexOf('*FEATURES*')).toBeLessThan(t.indexOf('*DECISIONS*'))
    expect(t.indexOf('*DECISIONS*')).toBeLessThan(t.indexOf('*HAZARDS*'))
  })

  it('OLDEST FIRST inside each group — the quiet three-week bug is not buried', () => {
    const brief = build(items)
    const bugs = brief.groups.find(g => g.type === 'bug')!.lines.map(l => l.ageDays)
    expect(bugs).toEqual([30, 2, 0])
  })

  it('age prints as "19 days", never as a date', () => {
    const brief = build([
      item({ id: 'aged', createdDays: 19, title: 'aged' }),
      item({ id: 'fresh', createdDays: 0, title: 'fresh' }), // else the day is quiet and nothing prints
    ])
    expect(brief.text).toContain('19 days')
    expect(brief.text).not.toMatch(/\d{4}-\d{2}-\d{2}/)
  })

  it('an unrecognised type is still shown rather than silently dropped', () => {
    const brief = build([item({ id: 'weird', type: 'mystery', createdDays: 0, title: 'odd one' })])
    expect(brief.text).toContain('*OTHER*')
    expect(brief.text).toContain('odd one')
  })
})

describe('the analysis applies to bugs, and to features only where they point somewhere', () => {
  it('decisions and hazards get no analysis at all — they are not located in code', () => {
    const brief = build([
      item({
        id: 'd', type: 'decision', is_internal: true, createdDays: 0, title: 'Decide on 9 locations',
        description: 'Decide what happens to 9 locations marked active with no Stripe record in the client list',
      }),
    ])
    const line = brief.groups.find(g => g.type === 'decision')!.lines[0]
    expect(line.placement).toBeNull()
    expect(brief.text).not.toContain('↳')
  })

  it('a bug always gets an analysis line, even when that line is "cannot place"', () => {
    const brief = build([item({ type: 'bug', title: 'zz', description: 'qqq zzz', createdDays: 0 })])
    expect(brief.text).toContain('↳')
  })
})

describe('internal items are labelled distinctly from owner reports', () => {
  const items = [
    item({ id: 'owner', type: 'bug', createdDays: 0, title: 'owner report', submitter: 'Lynette Ewy', location: 'Kansas City' }),
    item({ id: 'int', type: 'hazard', is_internal: true, createdDays: 0, title: 'internal hazard', submitter: 'Kevin' }),
  ]

  it('an internal item reads as [internal]; an owner report names the submitter and location', () => {
    const brief = build(items)
    expect(brief.text).toContain('[internal]')
    expect(brief.text).toContain('Lynette Ewy · Kansas City')
  })

  it('the internal item does NOT print a submitter name — it is not an owner report', () => {
    const brief = build(items)
    const internalLine = brief.text.split('\n').find(l => l.includes('[internal]'))!
    expect(internalLine).not.toContain('Kevin')
  })

  it('internal items are counted, and included rather than hidden', () => {
    const brief = build(items)
    expect(brief.internalCount).toBe(1)
    expect(brief.openCount).toBe(2)
  })
})

describe('mis-typed items are FLAGGED, never re-typed', () => {
  it('a bug whose description is plainly a request is flagged', () => {
    // Real row, filed as a bug.
    const it = item({
      type: 'bug', title: 'Nuturing',
      description: 'I have 200+ clients in nurturing, any way to bulk update and send them to client',
    })
    expect(mistypeFlag(it)).toBe('reads as a feature request')
  })

  it('the stored type is never changed', () => {
    const rows = [item({
      id: 'n', type: 'bug', createdDays: 0, title: 'Nuturing',
      description: 'any way to bulk update and send them to client',
    })]
    const brief = build(rows)
    expect(rows[0].type).toBe('bug')
    expect(brief.groups.find(g => g.type === 'bug')!.lines[0].item.type).toBe('bug')
    expect(brief.text).toContain('reads as a feature request')
  })

  it('an item reading as BOTH is left alone — the flag is conservative', () => {
    // "Snooze not available in Client section" is request-shaped and
    // defect-shaped at once. Flagging it would be noise.
    expect(mistypeFlag(item({ type: 'feature', title: 'Snooze Button', description: 'Snooze not available in Client section' }))).toBeNull()
  })

  it('a real bug is not flagged', () => {
    expect(mistypeFlag(item({ type: 'bug', title: 'Email cut off', description: "Email address is cut off if it's too long" }))).toBeNull()
  })
})

describe('suppression — a quiet day says nothing', () => {
  it('suppresses when nothing is new and nothing newly went stale', () => {
    const brief = build([
      item({ id: 'a', status: 'submitted', createdDays: 5 }),
      item({ id: 'b', status: 'under_review', createdDays: 40, touchedDays: 30 }),
    ])
    expect(brief.suppressed).toBe(true)
    expect(brief.text).toBe('')
  })

  it('does NOT suppress when something arrived today', () => {
    const brief = build([item({ id: 'a', createdDays: 0 })])
    expect(brief.suppressed).toBe(false)
    expect(brief.newCount).toBe(1)
  })

  it('does NOT suppress when something newly went quiet — the day it crosses 14', () => {
    // Untouched for exactly 14 days: stale now, not stale a day ago.
    const brief = build([
      item({ id: 'b', status: 'under_review', createdDays: 40, touchedDays: 14 }),
    ])
    expect(brief.newlyStaleCount).toBe(1)
    expect(brief.suppressed).toBe(false)
    expect(brief.text).toContain('JUST WENT QUIET')
  })

  it('an item quiet for a long time does not re-trigger every day', () => {
    const brief = build([
      item({ id: 'b', status: 'under_review', createdDays: 60, touchedDays: 45 }),
    ])
    expect(brief.newlyStaleCount).toBe(0)
    expect(brief.suppressed).toBe(true)
  })

  it('an empty queue is a quiet day, not a crash', () => {
    const brief = build([])
    expect(brief.suppressed).toBe(true)
    expect(brief.openCount).toBe(0)
  })
})

describe('the brief does NOT suggest fixes — that is a different build', () => {
  it('names where to look and stops there', () => {
    const brief = build([
      item({
        type: 'bug', createdDays: 0, title: 'x',
        description:
          'When entering a new lead on your phone, especially iPhone, the keyboard covers up the ' +
          'areas you need to type in, makes entering information slow, and I have to ask client ' +
          'same information again. Zee Bee comes off as incompetent',
      }),
    ])
    expect(brief.text).toContain('likely:')
    expect(brief.text.toLowerCase()).not.toContain('suggested fix')
    expect(brief.text).toContain('Starting points, not conclusions')
  })
})

// ─────────────────────────────────────────────────────────────────────
// THE HEARTBEAT ALLOWLIST — digest_runs now has two writers.
const svc = vi.hoisted(() => ({ rows: [] as any[], captured: [] as any[], filters: [] as any[] }))
vi.mock('@/lib/supabase-service', () => ({
  supabaseService: {
    from() {
      const b: any = {}
      b.select = () => b
      b.in = (col: string, vals: any[]) => { svc.filters.push([col, vals]); return b }
      b.order = () => b
      b.limit = () => Promise.resolve({
        data: svc.rows.filter(r =>
          svc.filters.every(([c, v]) => v.includes(r[c])),
        ),
        error: null,
      })
      b.insert = (rows: any) => { svc.captured.push(rows); return Promise.resolve({ error: null }) }
      return b
    },
  },
}))

describe('digest_runs liveness — the feedback brief must not answer for the webhook digest', () => {
  beforeEach(() => { svc.rows = []; svc.captured = []; svc.filters = [] })

  it('THE DEFECT: a fresh feedback-brief row must not make a dead webhook digest look alive', async () => {
    const { fetchLatestDigestRun } = await import('@/lib/digest-runs')
    svc.rows = [
      { ran_at: '2026-08-01T10:00:00Z', window_label: 'last 24h' },   // webhook digest, 14 days stale
      { ran_at: '2026-08-15T11:00:00Z', window_label: 'feedback brief' }, // today, different cron
    ]
    const { run } = await fetchLatestDigestRun()
    expect(run?.window_label).toBe('last 24h')
    expect(run?.ran_at).toBe('2026-08-01T10:00:00Z')
  })

  it('the historical "last 3h" cadence still counts as the webhook digest', async () => {
    const { fetchLatestDigestRun } = await import('@/lib/digest-runs')
    svc.rows = [{ ran_at: '2026-07-30T10:00:00Z', window_label: 'last 3h' }]
    const { run } = await fetchLatestDigestRun()
    expect(run?.window_label).toBe('last 3h')
  })

  it('the brief writes its own label, and records even a suppressed run', async () => {
    const { recordFeedbackBriefRun, FEEDBACK_BRIEF_LABEL } = await import('@/lib/digest-runs')
    await recordFeedbackBriefRun({ suppressed: true, text: '' }, { ok: false })
    expect(svc.captured[0].window_label).toBe(FEEDBACK_BRIEF_LABEL)
    expect(svc.captured[0].suppressed).toBe(true)
    expect(svc.captured[0].message_text).toBeNull()
  })

  it('a posted run stores the message text, so the brief is auditable after the fact', async () => {
    const { recordFeedbackBriefRun } = await import('@/lib/digest-runs')
    await recordFeedbackBriefRun({ suppressed: false, text: 'the brief' }, { ok: true })
    expect(svc.captured[0].posted).toBe(true)
    expect(svc.captured[0].message_text).toBe('the brief')
  })
})

// ─────────────────────────────────────────────────────────────────────
// THE ROUTE.
vi.mock('@/lib/feedback-brief-data', () => ({
  fetchFeedbackForBrief: vi.fn(async () => routeMock.result),
}))
vi.mock('@/lib/slack', () => ({
  postSlackMessage: vi.fn(async (text: string) => {
    routeMock.posted.push(text)
    return routeMock.slack
  }),
}))
const routeMock = vi.hoisted(() => ({
  result: { items: [] as any[], ok: true, internalSupported: true },
  posted: [] as string[],
  slack: { ok: true } as { ok: boolean; skipped?: string; error?: string },
}))

import { NextRequest } from 'next/server'
import { GET } from '@/app/api/cron/feedback-brief/route'

const URL_BASE = 'https://app.example.com/api/cron/feedback-brief'
const freshBug = () => ({
  id: 'r1', type: 'bug', status: 'submitted', title: 'x',
  description: 'the kanban board columns are wrong and a card is in the wrong column',
  created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  is_internal: false, submitter: 'Ankur Patel', location: 'Palm Beach',
})

describe('GET /api/cron/feedback-brief', () => {
  beforeEach(() => {
    delete process.env.CRON_SECRET
    routeMock.result = { items: [], ok: true, internalSupported: true }
    routeMock.posted = []
    routeMock.slack = { ok: true }
    svc.captured = []
  })

  it('FAILS CLOSED: 500 when CRON_SECRET is not configured', async () => {
    const res = await GET(new NextRequest(URL_BASE))
    expect(res.status).toBe(500)
    expect((await res.json()).error).toBe('cron_secret_not_configured')
    expect(routeMock.posted).toHaveLength(0)
  })

  it('401 on a wrong bearer token, and nothing is posted', async () => {
    process.env.CRON_SECRET = 'right'
    const res = await GET(new NextRequest(URL_BASE, { headers: { authorization: 'Bearer wrong' } }))
    expect(res.status).toBe(401)
    expect(routeMock.posted).toHaveLength(0)
  })

  it('401 with no credentials at all', async () => {
    process.env.CRON_SECRET = 'right'
    expect((await GET(new NextRequest(URL_BASE))).status).toBe(401)
  })

  it('accepts ?secret= for manual testing', async () => {
    process.env.CRON_SECRET = 'right'
    expect((await GET(new NextRequest(`${URL_BASE}?secret=right`))).status).toBe(200)
  })

  it('A QUIET DAY POSTS NOTHING AND RETURNS 200', async () => {
    process.env.CRON_SECRET = 'right'
    routeMock.result = {
      items: [{
        id: 'old', type: 'bug', status: 'submitted', title: 'old', description: 'old thing',
        created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
        updated_at: new Date(Date.now() - 5 * 86400000).toISOString(),
      }],
      ok: true, internalSupported: true,
    }
    const res = await GET(new NextRequest(`${URL_BASE}?secret=right`))
    expect(res.status).toBe(200)
    const body = await res.json()
    expect(body.suppressed).toBe(true)
    expect(body.posted).toBe(false)
    expect(routeMock.posted).toHaveLength(0)
  })

  it('a suppressed run still records the heartbeat — silence must not look like death', async () => {
    process.env.CRON_SECRET = 'right'
    await GET(new NextRequest(`${URL_BASE}?secret=right`))
    expect(svc.captured).toHaveLength(1)
    expect(svc.captured[0].suppressed).toBe(true)
  })

  it('posts when something is new', async () => {
    process.env.CRON_SECRET = 'right'
    routeMock.result = { items: [freshBug()], ok: true, internalSupported: true }
    const res = await GET(new NextRequest(`${URL_BASE}?secret=right`))
    expect(res.status).toBe(200)
    expect(routeMock.posted).toHaveLength(1)
    expect(routeMock.posted[0]).toContain('*BUGS*')
  })

  it('a failed READ is a 500, never a cheerful "0 open"', async () => {
    process.env.CRON_SECRET = 'right'
    routeMock.result = { items: [], ok: false, internalSupported: true }
    const res = await GET(new NextRequest(`${URL_BASE}?secret=right`))
    expect(res.status).toBe(500)
    expect((await res.json()).error).toBe('feedback_read_failed')
    expect(routeMock.posted).toHaveLength(0)
  })

  it('a missing SLACK_WEBHOOK_URL is a logged no-op, not a cron failure', async () => {
    process.env.CRON_SECRET = 'right'
    routeMock.result = { items: [freshBug()], ok: true, internalSupported: true }
    routeMock.slack = { ok: false, skipped: 'no_webhook_url' }
    const res = await GET(new NextRequest(`${URL_BASE}?secret=right`))
    expect(res.status).toBe(200)
    expect((await res.json()).skipped).toBe('no_webhook_url')
  })

  it('a Slack error surfaces as 502 so it shows in the cron logs', async () => {
    process.env.CRON_SECRET = 'right'
    routeMock.result = { items: [freshBug()], ok: true, internalSupported: true }
    routeMock.slack = { ok: false, error: 'slack_http_500' }
    const res = await GET(new NextRequest(`${URL_BASE}?secret=right`))
    expect(res.status).toBe(502)
  })
})

describe('the route is registered and configured like the digest it was modelled on', () => {
  const src = readFileSync('app/api/cron/feedback-brief/route.ts', 'utf8')

  it("declares nodejs runtime, force-dynamic, and force-no-store", () => {
    expect(src).toContain("export const runtime = 'nodejs'")
    expect(src).toContain("export const dynamic = 'force-dynamic'")
    // NOT redundant with force-dynamic — nested supabase-js GETs were served
    // frozen from Next's Data Cache for days (#95).
    expect(src).toContain("export const fetchCache = 'force-no-store'")
  })

  it('is registered in vercel.json as a daily cron', () => {
    const vercel = JSON.parse(readFileSync('vercel.json', 'utf8'))
    const cron = vercel.crons.find((c: any) => c.path === '/api/cron/feedback-brief')
    expect(cron).toBeTruthy()
    expect(cron.schedule).toMatch(/^0 \d+ \* \* \*$/)
  })

  it('does not collide with the webhook digest slot', () => {
    const vercel = JSON.parse(readFileSync('vercel.json', 'utf8'))
    const brief = vercel.crons.find((c: any) => c.path === '/api/cron/feedback-brief')
    const digest = vercel.crons.find((c: any) => c.path === '/api/cron/webhook-digest')
    expect(brief.schedule).not.toBe(digest.schedule)
  })
})
