// lib/feedback-placement.ts
//
// "Where does this report probably live?" — matching an owner's own words
// against docs/screen-map.json. Issue 248 step 2.
//
// ─── THE PREMISE THIS CORRECTS ────────────────────────────────────────
// The issue-247 scout judged that 25 of 28 open reports carried too little to
// locate, and cited TITLES as evidence: "Quo", "Guide", "Toggle Button",
// "bigger font for us tenured bees". That measurement was taken from titles and
// character counts. It was wrong, and the direction of the error matters: the
// titles are the thin part. Measured over the same 28 rows, the DESCRIPTIONS
// average 147 characters and only 5 fall under 40. "Quo" is a 253-character
// integration request naming a phone system and a business number.
//
// So this matcher reads the DESCRIPTION first and the title second. Title text
// is scored at TITLE_WEIGHT — it can break a tie, it cannot carry a placement.
// A title like "Problem with Engagement – Aug 2026" (autogenerated by the
// composer) must never be what places an item.
//
// ─── WHY `says` IS THE FIELD WE MATCH ─────────────────────────────────
// The map carries `says` — "how a non-technical person refers to this surface"
// — precisely for this. `surface` is written in our words; `says` is written in
// theirs, which is the vocabulary the reports actually arrive in. So `says`
// phrases score highest, `surface` contributes at a lower weight, and `nav` is
// ignored entirely (it is a one-word bucket name shared by dozens of entries —
// pure noise at this granularity).
//
// ─── WHY IDF, AND NOT A KEYWORD LIST ──────────────────────────────────
// A hand-written keyword list is a second map that rots independently of the
// first. Instead every token is weighted by how RARE it is across the 119
// entries' vocabulary. "client", "email" and "the" appear in dozens of entries
// and are therefore nearly worthless as evidence; "snooze", "thumbtack",
// "kanban" and "unsubscribe" appear in one or two and are decisive. This is
// what stops a description full of ordinary business words from lighting up
// forty entries at once with false confidence.
//
// ─── THE HONESTY RULE IS THE OUTPUT TYPE ──────────────────────────────
// A confident wrong pointer is worse than silence: it sends the reader to the
// wrong file and they trust it, because it was stated with confidence. So
// "cannot place this" is a first-class result, not a failure path — the
// function returns one of three shapes and the caller cannot get a file path
// out of the unplaced one. Ambiguity is reported AS ambiguity (a shortlist),
// never collapsed to a winner by rounding.

export interface ScreenMapEntry {
  id: string
  surface: string
  nav?: string
  file: string
  symbol?: string
  lines?: number[]
  says?: string[]
  note?: string
}

export type PlacementConfidence = 'confident' | 'possible' | 'none'

export interface PlacementCandidate {
  id: string
  surface: string
  file: string
  lines?: number[]
  score: number
  /** The owner's own words that matched — why this candidate is here at all. */
  matched: string[]
}

export interface Placement {
  confidence: PlacementConfidence
  candidates: PlacementCandidate[]
}

// ─── Words that must not be allowed to place anything ─────────────────
//
// IDF alone is not sufficient, and the first run over the real 28 proved it.
// IDF measures rarity WITHIN THE MAP, and rare-in-the-map is not the same as
// informative. "over", "behind", "make" and "many" each appear in one or two
// entries' phrasing, so IDF hands them near-maximum weight — and then a
// description containing "a new lead over the weekend" gets pulled toward
// whichever entry happened to use the word "over". Two classes of word have to
// be removed by name.

// 1. Generic English. Grammar, quantifiers, and verbs of no domain content.
// These carry no locating power in ANY codebase, so removing them costs
// nothing and stops the rare-in-map accident above.
const GENERIC_WORDS = [
  // Contractions, apostrophes already stripped by normalizeText.
  'arent', 'cant', 'didnt', 'doesnt', 'dont', 'hasnt', 'havent', 'im', 'isnt',
  'ive', 'shouldnt', 'thats', 'theres', 'theyre', 'wasnt', 'wont', 'wouldnt',
  'youre', 'youve', 'whos', 'lets',
  'a', 'all', 'an', 'and', 'another', 'any', 'anyone', 'anything', 'are', 'as', 'at',
  'back', 'be', 'been', 'before', 'behind', 'but', 'by', 'came', 'can', 'come',
  'comes', 'could', 'did', 'do', 'does', 'doesn', 'don', 'down', 'each', 'else',
  'even', 'ever', 'every', 'far', 'find', 'for', 'found', 'from', 'full', 'get',
  'give', 'go', 'going', 'had', 'has', 'hasn', 'have', 'haven', 'hear', 'her',
  'here', 'him', 'his', 'how', 'i', 'if', 'in', 'inside', 'instead', 'into',
  'is', 'it', 'its', 'itself', 'just', 'keep', 'know', 'let', 'like', 'long',
  'look', 'made', 'make', 'many', 'me', 'might', 'more', 'most', 'much', 'must',
  'my', 'need', 'needs', 'never', 'next', 'no', 'not', 'now', 'of', 'off', 'on',
  'once', 'one', 'only', 'or', 'other', 'our', 'out', 'over', 'own', 'part',
  'per', 'place', 'please', 'put', 'read', 'really', 'rest', 'said', 'same',
  'say', 'says', 'section', 'see', 'seen', 'she', 'short', 'should', 'side',
  'since', 'so', 'some', 'soon', 'start', 'still', 'sure', 'take', 'tell', 'than', 'that',
  'the', 'their', 'them', 'then', 'there', 'these', 'they', 'thing', 'things',
  'this', 'those', 'through', 'time', 'to', 'together', 'too', 'two', 'up',
  'us', 'use', 'used', 'very', 'want', 'was', 'way', 'we', 'well', 'went',
  'were', 'what', 'when', 'where', 'which', 'while', 'who', 'whole', 'why',
  'will', 'with', 'without', 'would', 'wouldn', 'yet', 'you', 'your',
]

// 2. The product's own name, and the vocabulary of reporting itself.
//
// THIS IS THE ONE THAT CAUSED REAL DAMAGE. "bee" and "hub" appear in the map
// (shell.ask-bee-hub's `says` is "ask bee hub"), are rare there, and therefore
// scored as decisive evidence. But every owner writes "Bee Hub" when describing
// anything at all — so the Thumbtack integration request and the Quo phone
// request were both placed CONFIDENTLY on the help panel, on the strength of
// the product's own name. That is precisely the confident-wrong-pointer this
// design exists to prevent.
//
// The same holds for "feedback", "problem", "issue" and "report": every row in
// this table is a report of a problem. A word that is present by construction
// is evidence of nothing.
const AMBIENT_WORDS = [
  'bee', 'bees', 'beehub', 'hub', 'crm', 'app', 'system', 'platform',
  'feedback', 'report', 'reported', 'problem', 'problems', 'issue', 'issues',
  'bug', 'broken', 'work', 'working', 'works',
]

const STOPWORDS = new Set([...GENERIC_WORDS, ...AMBIENT_WORDS])

// Apostrophes are DROPPED rather than kept, so "isn't" and "isnt" are one
// token. Keeping them made every contraction its own rare word — the map's
// phrasing ("a client isn't in the list", "the invite didn't arrive") gave
// "isn't" and "didn't" near-maximum IDF, and they turned up as evidence in the
// first run's matches. Contractions are grammar; they are stopworded below.
export function normalizeText(text: string): string {
  return String(text || '')
    .toLowerCase()
    .replace(/[‘’]/g, "'")
    .replace(/'/g, '')
    .replace(/[^a-z0-9]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
}

export function tokenize(text: string): string[] {
  return normalizeText(text)
    .split(' ')
    .filter(t => t.length > 2 && !STOPWORDS.has(t))
}

// ─── Tuning ───────────────────────────────────────────────────────────
// Every threshold here was set by running the matcher over the 28 real open
// items and reading the output, not by taste. They are deliberately
// conservative: the failure this design fears is a confident wrong pointer, so
// where a threshold was arguable it was set to demote rather than promote.

/** Title tokens count for this fraction of a description token. Title is a tie-breaker. */
const TITLE_WEIGHT = 0.35
/** A whole `says` phrase found verbatim in the text — the strongest signal available. */
const PHRASE_BONUS = 2.2
/** `surface` is our wording, not theirs. Present, but secondary to `says`. */
const SURFACE_WEIGHT = 0.45
/** Below this, nothing is worth showing at all. */
const FLOOR = 1.4
/**
 * A shortlist is only offered if its leader clears this. Below it, say nothing.
 *
 * THE LIMIT OF A LEXICAL MATCHER, STATED HONESTLY. There is no threshold that
 * separates a good single-word match from a bad one, and the real data proves
 * it: "notes" (from "really want notes to come over" → the notes box) and
 * "feed" (from "leads feed directly into Jobber" → the activity feed) both
 * occur in exactly one map entry, so both carry identical, maximum weight. One
 * is right and one is a verb that collided with a noun. No amount of tuning
 * tells them apart.
 *
 * So single weak candidates are kept rather than guessed at OR silently
 * dropped, and the defence is moved into the rendering: every candidate is
 * printed with the words that matched it. "possible — the notes box (matched:
 * feed)" is self-auditing in about one second of reading, which a bare file
 * path would not be.
 */
const POSSIBLE_MIN = 2.2
/** At or above this, AND corroborated, AND clear of the runner-up, one surface is named. */
const CONFIDENT_MIN = 3.2
/**
 * Top must DOMINATE the runner-up — not merely lead it — to be stated as one
 * answer rather than a shortlist.
 *
 * Set from the observed separation on the 28 real items, where the two correct
 * confident placements cleared the field by 2.36× and 2.45×, and the two wrong
 * ones (an automated-email complaint pulled onto Settings→Location by the word
 * "business"; a push-to-Jobber request pulled onto Settings→Profile by
 * "booking") both sat at exactly 1.73×. Word-sense collisions like those two
 * cannot be resolved lexically — "recent business" and "my business details"
 * are the same token — so the defence is to refuse to name one file unless
 * nothing else is close. Both now degrade to shortlists, which is the honest
 * reading of the evidence rather than a failure.
 *
 * Four data points is thin, and this threshold should be revisited as the
 * queue grows. It is deliberately set to under-claim: the cost of a demoted
 * good placement is a shortlist Kevin skims, and the cost of a promoted bad
 * one is a wasted morning in the wrong file.
 */
const CONFIDENT_MARGIN = 2.0
/**
 * A token this rare is DISTINCTIVE — it names a thing rather than describes one.
 * At 119 entries: df=1 → 4.08, df=2 → 3.68, df=5 → 2.99, df=10 → 2.38.
 * "notifications", "kanban", "unsubscribe" clear it; "email", "client", "list" do not.
 */
const DISTINCTIVE_MIN = 3.0
/** A shortlist keeps candidates within this fraction of the leader. */
const SHORTLIST_BAND = 0.55
const SHORTLIST_MAX = 3

interface EntryIndex {
  entry: ScreenMapEntry
  /** token -> weight contributed if the description contains it */
  tokens: Map<string, number>
  /** multi-word `says` phrases, normalized, for verbatim substring hits */
  phrases: string[]
  /** Breadth penalty — see buildPlacementIndex. */
  norm: number
}

export interface PlacementIndex {
  entries: EntryIndex[]
  idf: Map<string, number>
}

// Build once per run, not once per item — 28 items × 119 entries otherwise
// re-derives the same vocabulary 28 times.
export function buildPlacementIndex(entries: ScreenMapEntry[]): PlacementIndex {
  const docFreq = new Map<string, number>()
  const prepared = entries.map(entry => {
    const saysTokens = new Set<string>()
    const phrases: string[] = []
    for (const phrase of entry.says || []) {
      const norm = normalizeText(phrase)
      if (norm.split(' ').filter(w => !STOPWORDS.has(w)).length >= 2) phrases.push(norm)
      tokenize(phrase).forEach(t => saysTokens.add(t))
    }
    const surfaceTokens = new Set(tokenize(entry.surface))
    const all = new Set<string>()
    saysTokens.forEach(t => all.add(t))
    surfaceTokens.forEach(t => all.add(t))
    all.forEach(t => docFreq.set(t, (docFreq.get(t) || 0) + 1))
    return { entry, saysTokens, surfaceTokens, phrases }
  })

  const n = Math.max(1, prepared.length)
  const idf = new Map<string, number>()
  docFreq.forEach((df, token) => {
    // Standard smoothed IDF, floored at 0. A token in >half the entries lands
    // at ~0 and is thereby unable to place anything on its own.
    idf.set(token, Math.max(0, Math.log(n / (1 + df))))
  })

  const withTokens = prepared.map(p => {
    const tokens = new Map<string, number>()
    p.saysTokens.forEach(t => tokens.set(t, idf.get(t) || 0))
    p.surfaceTokens.forEach(t => {
      const w = (idf.get(t) || 0) * SURFACE_WEIGHT
      tokens.set(t, Math.max(tokens.get(t) || 0, w))
    })
    let mass = 0
    tokens.forEach(w => { mass += w })
    return { ...p, tokens, mass }
  })

  // ─── The breadth penalty ────────────────────────────────────────────
  // Entries are not equally sized. settings.location is a grab-bag ("my
  // business details", "the address on my emails", "the reply-to address", "my
  // company info", "the review link"); clients.close-won is four tight
  // phrases. Without a correction the grab-bag wins on surface area alone: on
  // the first real run, "a client forward an email ... offering a discount for
  // a google review" was placed CONFIDENTLY on settings.location, because
  // "business" + "review" + "email" happened to co-occur in its vocabulary.
  // Three ordinary words, three different meanings, one wrong file.
  //
  // Dividing by sqrt(mass / medianMass) makes the score "how much of THIS
  // entry's vocabulary did we hit", not "how many words did we hit at all". A
  // broad entry must be matched broadly to win. Median rather than mean so a
  // couple of very large entries don't drag the baseline.
  const masses = withTokens.map(p => p.mass).sort((a, b) => a - b)
  const median = masses[Math.floor(masses.length / 2)] || 1

  const indexed: EntryIndex[] = withTokens.map(p => ({
    entry: p.entry,
    tokens: p.tokens,
    phrases: p.phrases,
    norm: Math.max(0.6, Math.sqrt(Math.max(p.mass, 0.001) / median)),
  }))

  return { entries: indexed, idf }
}

function scoreEntry(
  indexed: EntryIndex,
  descTokens: Set<string>,
  titleTokens: Set<string>,
  descNorm: string,
): { score: number; matched: string[]; peak: number; phraseHit: boolean; hits: number } {
  let score = 0
  let peak = 0
  let hits = 0
  let phraseHit = false
  const matched: string[] = []

  indexed.tokens.forEach((weight, token) => {
    if (weight <= 0) return
    if (descTokens.has(token)) {
      score += weight
      peak = Math.max(peak, weight)
      hits++
      matched.push(token)
    } else if (titleTokens.has(token)) {
      score += weight * TITLE_WEIGHT
      hits++
      matched.push(token)
    }
  })

  // A whole phrase in the owner's vocabulary, verbatim. Scaled by the phrase's
  // own rarity so "the menu" cannot outweigh "snooze not available".
  for (const phrase of indexed.phrases) {
    if (!descNorm.includes(phrase)) continue
    const rarity = tokenize(phrase).reduce((s, t) => s + (indexed.tokens.get(t) || 0), 0)
    score += PHRASE_BONUS * Math.min(1, rarity / 2)
    if (rarity >= DISTINCTIVE_MIN) phraseHit = true
    matched.push(phrase)
  }

  return { score: score / indexed.norm, matched, peak, phraseHit, hits }
}

/**
 * Where does this report probably live?
 *
 * Reads `description` first; `title` only supplements it. Returns
 * confidence:'none' with no candidates whenever the evidence does not support
 * naming a file — that is a real answer, and the caller must print it as one.
 */
export function rankPlacements(
  item: { title?: string | null; description?: string | null },
  index: PlacementIndex,
): (PlacementCandidate & { corroborated: boolean })[] {
  const descNorm = normalizeText(item.description || '')
  const descTokens = new Set(tokenize(item.description || ''))
  const titleTokens = new Set(tokenize(item.title || ''))

  if (descTokens.size === 0 && titleTokens.size === 0) return []

  const scored: (PlacementCandidate & { corroborated: boolean })[] = []
  for (const indexed of index.entries) {
    const { score, matched, peak, phraseHit, hits } = scoreEntry(
      indexed, descTokens, titleTokens, descNorm,
    )
    if (score < FLOOR) continue
    // ─── The padding gate ───────────────────────────────────────────
    // A candidate must rest on TWO independent words from the description, or
    // on ONE distinctive enough to name a thing. Without this, entries sail
    // into shortlists on a single ordinary word: the Thumbtack request was
    // being offered three candidates whose entire evidence was the word "all",
    // and the Snooze request three whose evidence was "section". A shortlist
    // assembled from noise is padding, and padding is what teaches the reader
    // to stop reading. Better to return nothing and say so.
    if (hits < 2 && peak < DISTINCTIVE_MIN) continue
    scored.push({
      id: indexed.entry.id,
      surface: indexed.entry.surface,
      file: indexed.entry.file,
      lines: indexed.entry.lines,
      score: Math.round(score * 100) / 100,
      // Longest first: the phrase that matched is more informative than the
      // single tokens inside it.
      matched: Array.from(new Set(matched)).sort((a, b) => b.length - a.length).slice(0, 4),
      // ─── What "confident" has to be earned by ───────────────────────
      // Not accumulated score. Score accumulates from ordinary words, and
      // ordinary words are how the first run put an automated-email complaint
      // on the Settings→Location screen. Naming ONE file requires evidence of
      // a kind, not merely of a quantity:
      //   · a verbatim phrase in the owner's own vocabulary that is itself
      //     distinctive ("new leads", "the kanban"), OR
      //   · a distinctive token — one rare enough to name a thing rather than
      //     describe one — corroborated by at least one other hit from the
      //     description, so a single lucky word is never enough.
      // Everything else can still be a shortlist. It just cannot be an answer.
      corroborated: phraseHit || (peak >= DISTINCTIVE_MIN && hits >= 2),
    })
  }

  scored.sort((a, b) => b.score - a.score || a.id.localeCompare(b.id))
  return scored
}

export function placeFeedbackItem(
  item: { title?: string | null; description?: string | null },
  index: PlacementIndex,
): Placement {
  const scored = rankPlacements(item, index)
  if (scored.length === 0) return { confidence: 'none', candidates: [] }

  const top = scored[0]
  const second = scored[1]

  if (
    top.score >= CONFIDENT_MIN &&
    top.corroborated &&
    (!second || top.score >= second.score * CONFIDENT_MARGIN)
  ) {
    return { confidence: 'confident', candidates: [strip(top)] }
  }

  // Not confident. Is there enough to be worth a shortlist at all?
  if (top.score < POSSIBLE_MIN) return { confidence: 'none', candidates: [] }

  const band = scored
    .filter(c => c.score >= top.score * SHORTLIST_BAND)
    .slice(0, SHORTLIST_MAX)
    .map(strip)
  return { confidence: 'possible', candidates: band }
}

function strip(c: PlacementCandidate & { corroborated?: boolean }): PlacementCandidate {
  const { corroborated, ...rest } = c
  return rest
}
